### ISSUE TITLE
Can't create chat 

### ISSUE THREAD

**Issue by lucky-chap** [krasun/damngood.tools#2]
I am running your project locally, but when I try to upload a PDF file to chat with, this is the error I get. Can you help me out?

![damn](https://github.com/krasun/damngood.tools/assets/67266933/a2a4d199-825c-4136-809c-76f6a05fa35e)

**Comment by Yawmiej** [comment]
Seems to be an error from OpenAI and nothing to do with the application

You can check the OpenAI Error Codes over view. 
I can see a 429 error, which could be related to rate-limiting or exceeding your billing quota.

https://platform.openai.com/docs/guides/error-codes/api-errors

**Comment by krasun** [comment]
Thanks, @Yawmiej for clarifying. @lucky-chap, yes, the error relates to the OpenAI API.
