### ISSUE TITLE
Allow taking full page screenshots as well. 

### ISSUE THREAD

**Issue by jooseplall** [krasun/damngood.tools#4]
ScreenshotOne has a possibility to generate full page screenshots as well. 
Would be nice to have that option as well to generate full size screenshot for better overview of the webpages. 

https://screenshotone.com/docs/options/#full_page

**Comment by krasun** [comment]
Hi, Joosep. It is a great idea. Thanks for the proposal. I believe @EmmettNikolayev is working on it.

**Comment by krasun** [comment]
Hi, @jooseplall. I deployed a tool that allows you to [render the full-page screenshot of any website](https://damngood.tools/tools/full-page-screenshots). Thanks for suggestion.
